import React, { createContext, useContext, useState, useEffect, ReactNode, useCallback } from 'react';
import { Metric, MetricInput, DashboardStats, BurnoutRisk } from '../types';
import { useAuth } from './AuthContext';
import { format, subDays } from 'date-fns';
interface MetricsContextType { metrics:Metric[]; loading:boolean; addMetric:(i:MetricInput)=>Promise<void>; updateMetric:(id:string,i:MetricInput)=>Promise<void>; deleteMetric:(id:string)=>Promise<void>; getMetricByDate:(d:string)=>Metric|undefined; getStats:(d?:number)=>DashboardStats; getMetricsInRange:(d:number)=>Metric[]; }
const MetricsContext = createContext<MetricsContextType|undefined>(undefined);
function calcCS(e:number,f:number,s:number):number { return Math.max(0,Math.min(10,Math.round(((e+f-s)/10)*10)/10)); }
function calcBR(s:number,r?:number[]):BurnoutRisk { const a=r&&r.length>0?r.reduce((x,y)=>x+y,0)/r.length:s; if(a>=8)return'critical';if(a>=6)return'high';if(a>=4)return'moderate';return'low'; }
function genDemo(uid:string):Metric[] { const m:Metric[]=[]; for(let i=30;i>=1;i--){ const d=subDays(new Date(),i); const s=Math.floor(Math.random()*7)+2; const e=Math.floor(Math.random()*6)+4; const f=Math.floor(Math.random()*6)+3; const sl=Math.round((Math.random()*4+5)*10)/10; m.push({id:`demo-${i}`,user_id:uid,date:format(d,'yyyy-MM-dd'),sleep_hours:sl,stress_level:s,energy_level:e,focus_level:f,calm_score:calcCS(e,f,s),burnout_risk:calcBR(s),notes:i%5===0?'Feeling balanced today.':null,created_at:d.toISOString()}); } return m; }
export function MetricsProvider({children}:{children:ReactNode}) {
  const {user}=useAuth(); const [metrics,setMetrics]=useState<Metric[]>([]); const [loading,setLoading]=useState(true);
  useEffect(()=>{ if(!user){setMetrics([]);setLoading(false);return;} const s=localStorage.getItem('calmos_metrics'); if(s){setMetrics(JSON.parse(s));}else{const d=genDemo(user.id);setMetrics(d);localStorage.setItem('calmos_metrics',JSON.stringify(d));} setLoading(false); },[user]);
  const save=useCallback((m:Metric[])=>{setMetrics(m);localStorage.setItem('calmos_metrics',JSON.stringify(m));},[]);
  const addMetric=async(input:MetricInput)=>{ if(!user)return; if(metrics.find(m=>m.date===input.date))throw new Error('Entry exists for this date'); const rs=metrics.slice(-7).map(m=>m.stress_level);rs.push(input.stress_level); const n:Metric={id:`m-${Date.now()}`,user_id:user.id,date:input.date,sleep_hours:input.sleep_hours,stress_level:input.stress_level,energy_level:input.energy_level,focus_level:input.focus_level,calm_score:calcCS(input.energy_level,input.focus_level,input.stress_level),burnout_risk:calcBR(input.stress_level,rs),notes:input.notes||null,created_at:new Date().toISOString()}; save([...metrics,n].sort((a,b)=>a.date.localeCompare(b.date))); };
  const updateMetric=async(id:string,input:MetricInput)=>{ const rs=metrics.slice(-7).map(m=>m.stress_level); save(metrics.map(m=>m.id!==id?m:{...m,...input,calm_score:calcCS(input.energy_level,input.focus_level,input.stress_level),burnout_risk:calcBR(input.stress_level,rs),notes:input.notes||null})); };
  const deleteMetric=async(id:string)=>{save(metrics.filter(m=>m.id!==id));};
  const getMetricByDate=(date:string)=>metrics.find(m=>m.date===date);
  const getMetricsInRange=useCallback((days:number)=>{ if(days<=0)return metrics; const c=format(subDays(new Date(),days),'yyyy-MM-dd'); return metrics.filter(m=>m.date>=c); },[metrics]);
  const getStats=useCallback((days:number=30):DashboardStats=>{ const range=days>0?getMetricsInRange(days):metrics; if(range.length===0)return{avgCalmScore:0,avgStress:0,avgEnergy:0,avgFocus:0,avgSleep:0,totalEntries:0,currentStreak:0,burnoutRisk:'low'}; const avg=(a:number[])=>Math.round((a.reduce((x,y)=>x+y,0)/a.length)*10)/10; const sorted=[...metrics].sort((a,b)=>b.date.localeCompare(a.date)); let streak=0; for(let i=0;i<sorted.length;i++){const exp=format(subDays(new Date(),i),'yyyy-MM-dd');if(i===0&&sorted[0].date!==exp&&sorted[0].date!==format(subDays(new Date(),1),'yyyy-MM-dd'))break;if(sorted[i]?.date===exp)streak++;else if(i===0)streak++;else break;} const as=avg(range.map(m=>m.stress_level)); return{avgCalmScore:avg(range.map(m=>m.calm_score)),avgStress:as,avgEnergy:avg(range.map(m=>m.energy_level)),avgFocus:avg(range.map(m=>m.focus_level)),avgSleep:avg(range.map(m=>m.sleep_hours)),totalEntries:range.length,currentStreak:streak,burnoutRisk:calcBR(as)}; },[metrics,getMetricsInRange]);
  return <MetricsContext.Provider value={{metrics,loading,addMetric,updateMetric,deleteMetric,getMetricByDate,getStats,getMetricsInRange}}>{children}</MetricsContext.Provider>;
}
export function useMetrics(){const c=useContext(MetricsContext);if(!c)throw new Error('useMetrics must be within MetricsProvider');return c;}
